# Generated by Django 2.2.28 on 2024-03-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(help_text='轮播图编号', primary_key=True, serialize=False, verbose_name='轮播图编号')),
                ('img', models.CharField(blank=True, help_text='图片', max_length=255, null=True, verbose_name='图片 ')),
                ('url', models.CharField(blank=True, help_text='链接地址', max_length=255, null=True, verbose_name='链接地址 ')),
                ('index_radio', models.CharField(blank=True, help_text='是否首页', max_length=255, null=True, verbose_name='是否首页 ')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(help_text='编号', primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(blank=True, help_text='分类名称', max_length=255, null=True, verbose_name='分类名称 ')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, help_text='用户', null=True, verbose_name='用户')),
                ('goods_id', models.IntegerField(blank=True, help_text='商品', null=True, verbose_name='商品')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品收藏',
                'verbose_name_plural': '商品收藏',
                'db_table': 'collect',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(help_text='评论编号', primary_key=True, serialize=False, verbose_name='评论编号')),
                ('content', models.TextField(blank=True, help_text='评论内容', null=True, verbose_name='评论内容 ')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('user_id', models.IntegerField(blank=True, help_text='用户', null=True, verbose_name='用户')),
                ('goods_id', models.IntegerField(blank=True, help_text='商品编号', null=True, verbose_name='商品编号')),
                ('pid', models.IntegerField(blank=True, help_text='父评论ID', null=True, verbose_name='父评论ID')),
                ('puser_id', models.IntegerField(blank=True, help_text='父级用户ID', null=True, verbose_name='父级用户ID')),
                ('score', models.IntegerField(blank=True, help_text='评论星级', null=True, verbose_name='评论星级')),
            ],
            options={
                'verbose_name': '商品评论',
                'verbose_name_plural': '商品评论',
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(help_text='编号', primary_key=True, serialize=False, verbose_name='编号')),
                ('category_id', models.IntegerField(blank=True, help_text='商品分类', null=True, verbose_name='商品分类')),
                ('name', models.CharField(blank=True, help_text='商品名称', max_length=255, null=True, verbose_name='商品名称 ')),
                ('img', models.CharField(blank=True, help_text='商品图片', max_length=255, null=True, verbose_name='商品图片 ')),
                ('content', models.TextField(blank=True, help_text='商品介绍', null=True, verbose_name='商品介绍 ')),
                ('price', models.FloatField(blank=True, help_text='价格', null=True, verbose_name='价格 ')),
                ('business', models.CharField(blank=True, help_text='销售商家', max_length=255, null=True, verbose_name='销售商家 ')),
                ('province', models.CharField(blank=True, help_text='商家省份', max_length=255, null=True, verbose_name='商家省份 ')),
                ('city', models.CharField(blank=True, help_text='商家城市', max_length=255, null=True, verbose_name='商家城市 ')),
                ('sales', models.IntegerField(blank=True, help_text='销售量', null=True, verbose_name='销售量')),
                ('links', models.CharField(blank=True, help_text='数据来源', max_length=255, null=True, verbose_name='数据来源 ')),
                ('views', models.IntegerField(blank=True, help_text='浏览量', null=True, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(help_text='编号', primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(blank=True, help_text='登录账户', max_length=255, null=True, verbose_name='登录账户 ')),
                ('name', models.CharField(blank=True, help_text='姓名', max_length=255, null=True, verbose_name='姓名 ')),
                ('user_id', models.IntegerField(blank=True, help_text='所属用户', null=True, verbose_name='所属用户')),
                ('phone', models.CharField(blank=True, help_text='联系电话', max_length=255, null=True, verbose_name='联系电话 ')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Membertags',
            fields=[
                ('id', models.AutoField(help_text='编号', primary_key=True, serialize=False, verbose_name='编号')),
                ('user_id', models.IntegerField(blank=True, help_text='用户编号', null=True, verbose_name='用户编号')),
                ('category_id', models.IntegerField(blank=True, help_text='分类编号', null=True, verbose_name='分类编号')),
            ],
            options={
                'verbose_name': '用户标签',
                'verbose_name_plural': '用户标签',
                'db_table': 'membertags',
            },
        ),
    ]
