# Generated by Django 2.2.28 on 2024-03-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(blank=True, help_text='标题', max_length=255, null=True, verbose_name='标题 ')),
                ('content', models.TextField(blank=True, help_text='内容', null=True, verbose_name='内容 ')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('user_id', models.IntegerField(blank=True, help_text='发布者', null=True, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '网站公告',
                'verbose_name_plural': '网站公告',
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(help_text='权限名称', max_length=255, null=True, verbose_name='权限名称')),
                ('path', models.CharField(help_text='路径', max_length=255, null=True, verbose_name='路径')),
                ('orders', models.IntegerField(blank=True, help_text='顺序', null=True, verbose_name='顺序')),
                ('icon', models.CharField(help_text='图标', max_length=255, null=True, verbose_name='图标')),
                ('page', models.CharField(help_text='页面路径', max_length=255, null=True, verbose_name='页面路径')),
                ('auth', models.CharField(help_text='权限', max_length=255, null=True, verbose_name='权限')),
                ('p_id', models.IntegerField(blank=True, help_text='父ID', null=True, verbose_name='父ID')),
                ('deleted', models.IntegerField(blank=True, default=0, help_text='逻辑删除', null=True, verbose_name='逻辑删除')),
                ('type', models.IntegerField(blank=True, help_text='类型', null=True, verbose_name='类型')),
                ('hide', models.BooleanField(blank=True, help_text='是否隐藏', null=True, verbose_name='是否隐藏')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '权限菜单表',
                'verbose_name_plural': '权限菜单表',
                'db_table': 'sys_permission',
            },
        ),
        migrations.CreateModel(
            name='SysDict',
            fields=[
                ('id', models.AutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('code', models.CharField(help_text='编码', max_length=255, verbose_name='编码')),
                ('value', models.CharField(help_text='内容', max_length=255, null=True, verbose_name='内容')),
                ('type', models.CharField(help_text='类型', max_length=10, null=True, verbose_name='类型')),
                ('deleted', models.IntegerField(blank=True, default=0, help_text='逻辑删除', null=True, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '数据字典表',
                'verbose_name_plural': '数据字典表',
                'db_table': 'dict',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('username', models.CharField(db_index=True, help_text='用户名', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(blank=True, help_text='密码', max_length=255, null=True, verbose_name='密码')),
                ('name', models.CharField(blank=True, help_text='昵称', max_length=255, null=True, verbose_name='昵称')),
                ('email', models.EmailField(blank=True, help_text='邮箱', max_length=255, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=255, null=True, verbose_name='地址')),
                ('avatar', models.CharField(blank=True, help_text='头像', max_length=255, null=True, verbose_name='头像')),
                ('uid', models.CharField(blank=True, help_text='用户唯一id', max_length=100, null=True, verbose_name='用户唯一id')),
                ('role', models.CharField(blank=True, help_text='角色', max_length=255, null=True, verbose_name='角色')),
                ('deleted', models.IntegerField(blank=True, default=0, help_text='逻辑删除', null=True, verbose_name='逻辑删除')),
                ('score', models.IntegerField(blank=True, default=0, help_text='积分', null=True, verbose_name='积分')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'sys_user',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(help_text='角色名称', max_length=255, verbose_name='角色名称')),
                ('flag', models.CharField(help_text='唯一标识', max_length=255, verbose_name='唯一标识')),
                ('deleted', models.IntegerField(blank=True, default=0, help_text='逻辑删除', null=True, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('permission', models.ManyToManyField(to='user_management.Permission')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
                'db_table': 'sys_role',
            },
        ),
    ]
